server:
   port: 8080   
spring:
   application:
      name: gateway-service  
   cloud:
      gateway:
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "http://localhost:4200/"
              allowedMethods: "*"
              allowedHeaders: "*"
        routes:
          - id: userservice
            uri: http://localhost:8001/
            filters:
              - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            predicates:
             - Path=/user/**
          - id: jobservices
            uri: http://localhost:8000/
            filters:
              - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            predicates:
             - Path=/job/**