spring:
  application:
    name: job services
  datasource:
    url: jdbc:mysql://localhost:3306/musedb?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
 port: 8000

eureka:
  instance:
    hostname: localhost